name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16, 18]
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: 'install:linux:dep'
        run: sudo apt-get install -y libgbm-dev
      - name: 'yarn:install'
        run: yarn install --frozen-lockfile
        env:
          CI: true
      - name: build
        run: yarn build
      - name: test
        run: yarn test
